import 'package:google_sign_in/google_sign_in.dart';
import '../models/connected_account.dart';
import '../repositories/connected_account_repository.dart';

class GmailConnectionService {
  final ConnectedAccountRepository _accountRepo = ConnectedAccountRepository();
  
  final GoogleSignIn _googleSignIn = GoogleSignIn(
    clientId: '396040336267-nnrfode235hjk7hknrod2nq7bppjpv7b.apps.googleusercontent.com',
    scopes: [
      'email',
      'https://www.googleapis.com/auth/gmail.readonly',
    ],
  );

  Future<bool> isGmailConnected() async {
    final accounts = await _accountRepo.fetchMyAccounts();
    return accounts.any((a) => a.provider == 'gmail' && a.status == 'connected');
  }

  Future<void> connectGmail(String userId) async {
    try {
      final GoogleSignInAccount? account = await _googleSignIn.signIn();
      if (account == null) return; // User cancelled

      // After successful consent, we save the connection to Supabase
      await _accountRepo.upsertAccount(ConnectedAccount(
        id: '', // Generated by Supabase
        userId: userId,
        provider: 'gmail',
        providerEmail: account.email,
        status: 'connected',
        accessScope: 'gmail.readonly',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ));
    } catch (error) {
      print('Gmail connection error: $error');
      rethrow;
    }
  }

  Future<String?> getAccessToken() async {
    final account = await _googleSignIn.signInSilently();
    if (account == null) return null;
    final auth = await account.authentication;
    return auth.accessToken;
  }

  Future<void> disconnectGmail(String id) async {
    await _accountRepo.deleteAccount(id);
  }
}
