// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUUs4GyXTGJD9TLakv3iGvbSO1aLH2AXo',
    appId: '1:653322528670:web:d80a6d05fe416db74f188f',
    messagingSenderId: '653322528670',
    projectId: 'vello-application',
    authDomain: 'vello-application.firebaseapp.com',
    storageBucket: 'vello-application.firebasestorage.app',
    measurementId: 'G-D29L5HSS8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-WcoDap-5SuiqR3QZEcPj3cDEoyLpcQg',
    appId: '1:653322528670:android:c3e38f6463c8c6de4f188f',
    messagingSenderId: '653322528670',
    projectId: 'vello-application',
    storageBucket: 'vello-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4fZUSHN4bFna-pEZqPXfQ4vpLQ7UTzA',
    appId: '1:653322528670:ios:bd849e95ee8a6ebf4f188f',
    messagingSenderId: '653322528670',
    projectId: 'vello-application',
    storageBucket: 'vello-application.firebasestorage.app',
    iosBundleId: 'com.example.velloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4fZUSHN4bFna-pEZqPXfQ4vpLQ7UTzA',
    appId: '1:653322528670:ios:bd849e95ee8a6ebf4f188f',
    messagingSenderId: '653322528670',
    projectId: 'vello-application',
    storageBucket: 'vello-application.firebasestorage.app',
    iosBundleId: 'com.example.velloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUUs4GyXTGJD9TLakv3iGvbSO1aLH2AXo',
    appId: '1:653322528670:web:f1a812349dfc73974f188f',
    messagingSenderId: '653322528670',
    projectId: 'vello-application',
    authDomain: 'vello-application.firebaseapp.com',
    storageBucket: 'vello-application.firebasestorage.app',
    measurementId: 'G-N6WY5KTT63',
  );
}